version: 1
formatters:
  defaultFormatter:
    format: '[%(asctime)s][%(levelname)s][%(name)s][%(funcName)s()] %(message)s'
handlers:
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: defaultFormatter
    filename: cdp.log
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: defaultFormatter
    stream: ext://sys.stdout
loggers:
  nl2sql:
    level: INFO
    handlers: [console, file]
    propagate: no
  pgvector_handler:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console]